spring.application.name=linkedIn-Post-Generator

spring.datasource.url=jdbc:mysql://localhost:3306/linkedin_ai
spring.datasource.username=root
spring.datasource.password=saajid@2009

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

server.port=8080

# JWT Configuration
app.jwt.secret=your-super-secret-key-min-256-bits-long-for-security-purposes-change-in-production-environment
app.jwt.expiration=86400000

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

gemini.api.key=AIzaSyCQfUuuMBeoDZvLMgdM6Ij6maT2K7HNcAM

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=959334023629-lfiitd8hp829gp36puakr0ttpff3kut5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

gemini.api.key=AIzaSyCQfUuuMBeoDZvLMgdM6Ij6maT2K7HNcAM