spring.application.name=linkedIn-Post-Generator

spring.datasource.url=jdbc:mysql://localhost:3306/linkedin_ai
spring.datasource.username=root
spring.datasource.password=saajid@2009

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

server.port=8080

# Session Configuration (required for OAuth2 NONCE validation)
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax
server.servlet.session.timeout=30m

# JWT Configuration (7 days = 604800000 milliseconds)
app.jwt.secret=your-super-secret-key-min-256-bits-long-for-security-purposes-change-in-production-environment
app.jwt.expiration=604800000

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

gemini.api.key=AIzaSyCQfUuuMBeoDZvLMgdM6Ij6maT2K7HNcAM


linkedin.client.id=86uo2dxycaryb5
linkedin.client.secret=WPL_AP1.8q2hjqvhv9Dxik6i.D2M3nQ==
linkedin.redirect.uri=http://localhost:8080/login/oauth2/code/linkedin
